### ISSUE TITLE
Feedback as requested on Reddit

### ISSUE THREAD

**Issue by benwainwrightcinch** [RaffBenato/Truco#2]
Hey there!

I came to this repo via your comment on Reddit, where you've requested some feedback. There is a fair amount of code to read here so I'm not going to go through it in detail, but there is definitely a couple of pointers I can give you.

### Keep state as localised as possible

Global variables are generally a bad thing; this is because when bugs appear, once you track down the erroneous variable that has the wrong value, you then have to work out what has changed it, and if you've got lots of globally scoped variables, it could be _anything_. This leads on to a follow-on point:

### Don't mutate state that isn't local to the function (e.g. array or object references passed in from *outside* the function)

So for example, your `shuffle` function is passed in the deck as argument and *directly changes its contents*. This is something you *can* do, and _sometimes_ there is some very good reasons why you might do this, but generally functions that simply take in a variable and return a value (rather than changing the contents of the original variable), are much easier to reason about.

We can actually solve both the above problems by trying to keep our functions as [pure](https://en.wikipedia.org/wiki/Pure_function) as possible: instead of writing functions that mutate input arguments or the state of globally scoped variables, consider writing functions that create *entirely new state* and return that state. To progress your algorithm, you simply take that state and pass it into the next function. So for example, instead of this:

```JavaScript
let deck = [] // global variable

function createDeck() {
  let p = 1;
  let a = 0;

  // Side note: hard coded numbers like this are often referred to as 'magic numbers' which is a
  //                   well established anti-pattern. You can google this :-)
  for (let c = 0; c < 10; c++) {
    for (let i = 0; i < 4; i++) {
      card = [a, cardNumbers[c], cardSuits[i], p]; 

      deck.push(card); // mutating a global variable. Noo :-(
      a++;
    }
    p++;
  }
}

function shuffle(arr) {
  let currentIndex = arr.length;
  let randomIndex;

  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    [arr[currentIndex], arr[randomIndex]] = [
      arr[randomIndex],
      arr[currentIndex],
    ];
  }

  return arr;
}

btnNextRound.addEventListener("click", function () {
   // ...lots of other stuff
  createDeck();
  shuffle(deck);
});
```
You can do this:

```JavaScript

function createDeck() {
  /*
   * note that arrays are const because even though you are mutating them with
   * push, you aren't changing the *reference* ie. it isn't *pointing to a new array*
   */
  const deck = [] // No longer global

  let p = 1;
  let a = 0;

  // Side note: hard coded numbers like this are often referred to as 'magic numbers' which is a
  //                   well established anti-pattern. You can google this :-)
  for (let c = 0; c < 10; c++) {
    for (let i = 0; i < 4; i++) {
      /*
       * Note since `cardNumbers` and `cardSuites` are never going to change, it is fine to refer
       * to define them outside of the function and refer to them within it. We call
       * these 'constants'.
       *
       * Since JavaScript won't *stop* you mutating constants (the const keyword only stops
       * you changing the 'reference' as noted above), it is good practice to
       * distinguish them from variables that *will* change to make sure you don't do it by mistake
       *  Idiomatically in JavaScript, we do this by putting them in CAPS_CASE, so you'd define them
       * as
       * const CARD_NUMBERS = [...]
       */

      card = [a, cardNumbers[c], cardSuits[i], p];

      deck.push(card);
      a++;
    }
    p++;
  }
  return deck;
}

function shuffle(deck) {
  const returnVal = [...deck] // This will perform a shallow *clone* of the input array
  let currentIndex = arr.length;
  let randomIndex;

  while (currentIndex != 0) {
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    [returnVal[currentIndex], returnVal[randomIndex]] = [
      returnVal[randomIndex],
      returnVal[currentIndex],
    ];
  }

  return returnVal;
}

/*
 * I haven't changed this because some of it is just copied and pasted from your code, but if you find yourself
 * writing in a professional setting ever, please don't abbreviate variable names! You'd be surprised how much confusion
 * is caused by abbreviations that are obvious to one developer but not another.
 */
btnNextRound.addEventListener("click", function () {
   // ...lots of other stuff

  const deck = createDeck();
  const shuffledDeck = shuffle(deck);

  // ...do more things with shuffled deck
});
```

Because functions are now only acting on local state, when a bug appears it will generally be much easier to narrow the bug down to the misbehaving function and to identify what has gone wrong.

usually, when explaining the above to beginners, they will say "ok, but surely creating new state every time will impact the performance?". The answer to this question is *not really*; modern computers are really, really fast and JavaScript is now a compiled language. There *may* come a point where you need to think about optimisations like this but writing code that is easier to read, debug and reason about should always be your primary concern. If you *start* to have performance issues, that is when you start making performance optimisations and not before.

There are other solutions to this problem; mine is moving you towards what is known as 'functional' programming. Advocates of 'object oriented' programming might suggest a different approach; very few experienced developers would disagree with the idea that you really shouldn't be using global variables *at all*. If you find yourself creating a variable at the top level that is not a 'constant' (see the comment above), then that is definitely a red flag. If the approach I've described above doesn't seem to fit, find someone and ask them 'how do I do this without using global variables'.

### Comment **why** not **what**

Too much commenting is generally considered a code smell. If it is necessary to write a comment to explain what a block of code does, it probably means your function isn't named well enough, or your code is too terse. Rather than commenting, focus on variable and function names that describe exactly what is going on (we like to call this 'self documenting code'). Whenever you feel the need to describe a 'paragraph' of code with a comment, try breaking that code out into a function and describing it with the function name. 

Every now and again, you will write code that is kind of esoteric or hacky. Its very clear *what* you are doing because you've named everything cleanly and broken the code down well, but perhaps you are doing something that is contrary to commonly understood best practice, or just something that might cause the average developer to go 'wtf'. In those situations, it's generally appropriate to write comments. But in this situation, don't tell me *what* you have done, this should already be clear. Tell me *why* you have done it.

**Comment by RaffBenato** [comment]
Wow thank you so much for your feedback, it is incredibly kind of you to take the time to do that.
Your feedback is exactly the kind of thing I was looking for, I dont expect people to go through a load of code from a total beginner and find lots of mistakes but your general concepts were very helpful and I will try and adopt them in the future. 
This code has kind of got away from me now but I will try and get it to work, as I feel like I am about 80% of the way there and as I learn more in my course and with insight from experienced people like you I will look to change it or maybe start again from zero.
Thanks again, I fully understand what you pointed out and most importantly the reasons for it.
All the best
